### PR TITLE
Android specific README.md changes

### PR DESCRIPTION
**Pull request by DynamicDonkey**
Fixing a couple issues in the README.md for Android specific contributors, including a specific version of Node.js as latest and LTS have a regex issue, and teaching the user how to generate a debug.keystore required to test on a physical device.

### CODE REVIEW

**Comment by isabellabrookes** [comment]
@DynamicDonkey make sure it's merging to the right branch

**Comment by adilanchian** [comment]
@isabellabrookes @DynamicDonkey Went ahead and changed the branch to release-1.0 :)

**Comment by adilanchian** [comment]
@DynamicDonkey - Throwing a bump on here :)

**Comment by adilanchian** [comment]
Closing PR as I made the changes locally!

**Comment by isabellabrookes** [comment]
@all-contributors please add @DynamicDonkey for doc

**Pull request closed without merging**
